ucdavis/cecdss

package-lock.json
package.json
src/components/Map/MapContainer.tsx
src/components/Results/ResultsCharts.tsx

move to scatter chart with some other stuff

work on sensitivity analysis

---

src/components/Map/ExternalLayerLegend.tsx
src/components/Map/ExternalLayerSelection.tsx
src/components/Map/Layers/OwnershipLegend.tsx
src/components/Map/MapContainer.tsx
src/components/Shared/config.ts

Added ownership to map layer

---

src/components/Map/GeoJsonLayers.tsx
src/components/Map/HeatmapLayers.tsx

closes #61 
Had to include keys into the returning elements in the else statement

Fixed key error

---

src/components/Map/MapContainer.tsx

Allowed map to zoom out when run model button is clicked

---

package-lock.json
package.json
src/components/Inputs/InputContainer.tsx
src/components/Inputs/validation.ts
src/components/Map/MapContainer.tsx
src/models/CHPClasses.ts
src/models/GPClasses.ts
src/models/GPOClasses.ts
src/models/Schemas.ts

Starter for validation project

---

src/components/Map/MapContainer.tsx

Removed duplicate clusters and errors

---

src/components/Map/MapContainer.tsx
src/components/Results/ResultsExport.tsx
src/components/Results/ResultsTables.tsx
src/models/Types.ts

include location with allyearResults

---

src/components/Map/MapContainer.tsx

Displayed zoom after run model button is pressed

---

src/components/Map/ExternalLayerLegend.tsx
src/components/Map/ExternalLayerSelection.tsx
src/components/Map/Layers/UrbanCitiesLegend.tsx
src/components/Map/MapContainer.tsx

Added urban city layer

---

src/components/Map/ExternalLayerLegend.tsx
src/components/Map/ExternalLayerSelection.tsx
src/components/Map/Layers/CountyLegend.tsx
src/components/Map/MapContainer.tsx

Added CountyLegend and County lines on map

---

src/components/Map/MapContainer.tsx

Added scale control to map

---

src/components/Map/MapContainer.tsx
src/components/Results/ResultsExport.tsx
src/components/Results/ResultsTables.tsx
src/models/Types.ts

Added facilityCoordinates and biomassCoordinates

---

package-lock.json
src/App.css
src/components/Map/ClusterTransportationRoutesLayer.tsx
src/components/Map/MapContainer.tsx

Also allow toggling of other layers

new cluster transportation route layer

---

src/App.css

Removed height from layers container to allow moving and scrolling

---

src/components/Results/ResultsExport.tsx
src/components/Results/Technoeconomic/TechnoeconomicTables.tsx

TEA totals should be averaged per year

---

src/components/Inputs/Frcs/FrcsInputsContainer.tsx
src/components/Results/LCA/LCAResults.tsx
src/components/Results/ResultsTables.tsx
src/components/Results/Technoeconomic/TechnoeconomicTables.tsx

resolve #101
resolve #102
resolve #103

Made some small fixes

---

src/components/Map/MapContainer.tsx
src/components/Results/Frcs/FrcsTables.tsx
src/components/Results/LCA/LCATables.tsx
src/components/Results/ResultsContainer.tsx
src/components/Results/Technoeconomic/TechnoeconomicTables.tsx

Biomass units should be BDT: Bone Dry Ton (short ton)
Some total quantities should be divided by the number of years

Correct biomass units and calculations of total quantities

---

src/components/Inputs/Technoeconomic/BasicTeaInputs.tsx
src/components/Inputs/Technoeconomic/ElectricalAndFuelBaseYearInput.tsx
src/components/Inputs/Technoeconomic/GasificationPower/ElectricalAndFuelBaseYearInputGP.tsx

correct capacity factor unit

---

public/index.html
src/components/Map/MapContainer.tsx
src/components/Results/ResultsExport.tsx
src/components/Results/ResultsTables.tsx

update way app handles inputs and capital cost outputs

---

package-lock.json
package.json
src/components/Inputs/Frcs/FrcsInputsContainer.test.tsx
src/components/Inputs/Frcs/FrcsInputsContainer.tsx
src/components/Inputs/InputContainer.tsx
src/components/Map/MapContainer.tsx
src/components/Results/Frcs/FrcsClusterResultsContainer.tsx
src/models/Types.ts

- Updated frcs npm package to v1.2.1
- Created entries in the user interface for the new frcs inputs 
- Created an entry for expansion factor
- Passed the new frcs inputs and the expansion factor to the backend

Update frcs npm to v1.2.1 and create entried for new inputs

---

src/components/Map/MapContainer.tsx

Escalate labor costs and ppi

---

src/components/Map/MapContainer.tsx

Goes with backend updates which handle timeout differently and wrap api calls in try/catch to send meaningful error codes/messages.  Right now we treat every error exactly the same.
Will handle API errors related to code or timeout.  If there is somehow an unhandled error we will not get any useful response.  This could be circumvented by wrapping our fetch in a timeout handler, but doesn't seem that useful currently.

display message on API errors

---

package-lock.json
package.json
src/components/Map/MapContainer.tsx
src/models/Types.ts

Send combined capital cost to backend for LCA calculations

Use @ucdavis/lca v1.6.0

---

src/components/Map/MapContainer.tsx
src/components/Results/Technoeconomic/TechnoeconomicTables.tsx
src/models/Types.ts

Display updated Biomass Fuel Cost and Energy Revenue Required

---

src/App.css
src/components/Inputs/InputContainer.tsx

Revert "moving fixed divs outside of eachother"

---

src/components/Inputs/Technoeconomic/BasicTeaInputs.tsx
src/components/Inputs/Technoeconomic/ElectricalAndFuelBaseYearInput.tsx
src/components/Inputs/Technoeconomic/ExpensesBaseYearInput.tsx
src/components/Inputs/Technoeconomic/GasificationPower/ExpensesBaseYearInputGP.tsx
src/components/Inputs/Technoeconomic/GasificationPower/GasificationPower.tsx
src/components/Inputs/Technoeconomic/GenericCombinedHeatPower/CombinedHeatAndPower.tsx
src/components/Inputs/Technoeconomic/GenericPowerOnly/GenericPowerOnly.tsx
src/components/Inputs/Technoeconomic/TechnoeconomicInputs.tsx
src/models/CHPClasses.ts
src/models/GPClasses.ts
src/models/GPOClasses.ts

Scale o&m cost

---

src/components/Results/ResultsExport.tsx
src/components/Results/ResultsTables.tsx

added annual generation to outputs

---

src/components/Map/MapContainer.tsx

default commercial thin + chip

default to treatment 3

---

src/Resources/Constants/index.ts
src/staticwebapp.config.json

- Added the static web app config file to fix the routing issue in prod.

Static Web App Config

---

src/Platform/App/components/Inputs/InputContainer.tsx
src/Platform/App/components/Map/Layers/BasicFeedstockCompetitionLegend.tsx
src/Platform/App/components/Map/Layers/PlantLegend.tsx
src/Platform/App/components/Map/MapContainer.tsx

- Arcgis feature layer APIs updated for transmission, fire and power plants. 
- Legends UI Fix
- Added progress bar to show feature loading
- Removed unwanted imports

ArcGis Layers Update and UI Fixes

---

.github/workflows/web-deploy.yml
README.md

- New dev guide link added
- Env setting in build and deploy job + some debugging

README updated

---

README.md
src/Platform/App/components/Inputs/InputContainer.tsx
src/Platform/App/components/Map/ExternalLayerLegend.tsx
src/Platform/App/components/Map/ExternalLayerSelection.tsx
src/Platform/App/components/Map/Layers/OwnershipLegend.tsx
src/Platform/App/components/Map/MapContainer.tsx
src/Platform/App/components/Results/ResultsContainer.tsx
src/Platform/App/components/Utils/config.ts
src/Styles/App.css

- Some UI updates to the model page
- `config.ts` file reverted
- `README` updated

UI updates

---

src/Platform/App/components/Map/MapContainer.tsx
src/Platform/App/components/Results/ResultsCharts.tsx
src/Platform/App/components/Utils/mockData.ts
src/Platform/App/models/CHPClasses.ts
src/Platform/App/models/GPClasses.ts
src/Platform/App/models/GPOClasses.ts
src/Platform/App/models/Schemas.ts
src/Resources/Constants/index.ts

- Change the year to 2025 
- Graph responsiveness added
- User guide link changed

Some changes and fixes
